### ISSUE TITLE
Customize and update theme

### ISSUE THREAD

**Issue by IrisDroidology** [IrisDroidology/portfolio#3]
Add portfolio, bio, etc

**Comment by IrisDroidology** [comment]
Need to add a header image, and a full portfolio on the portfolio.html page

**Comment by IrisDroidology** [comment]
Full portfolio added - see issue https://github.com/IrisDroidology/portfolio/issues/6

**Comment by Shivansh2407** [comment]
Can I also help you out on this

**Comment by IrisDroidology** [comment]
Finding it hard to find the cover image

**Comment by IrisDroidology** [comment]
> 
> 
> Can I also help you out on this

Hey mate, what are you wanting to help with?

**Comment by IrisDroidology** [comment]
See issue https://github.com/IrisDroidology/portfolio/issues/10

**Comment by IrisDroidology** [comment]
Theme found, closing comment
